name = "ITL_Utils"
uuid = "0633fd05-e604-4f1f-b2fc-f5591957addd"
authors = ["Surya Chandan Dhulipala <suryachandan.dhulipala@nrel.gov>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
